import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // const result = await prisma.chords.createMany({
  //   data: [
  //     {
  //       strings: "X 0 2 2 2 0",
  //       fingering: "X X 2 3 4 X",
  //       chordName: "A,,,",
  //       enharmonicChordName: "A,,,",
  //       voicingID: 1,
  //       tones: "A,C#,E",
  //     },
  //     {
  //       strings: "X 0 2 2 1 0",
  //       fingering: "X X 2 3 1 X",
  //       chordName: "A,m,,",
  //       enharmonicChordName: "A,m,,",
  //       voicingID: 2,
  //       tones: "A,C,E",
  //     },
  //     {
  //       strings: "X 0 2 0 2 0",
  //       fingering: "X X 2 X 3 X",
  //       chordName: "A,,7,",
  //       enharmonicChordName: "A,,7,",
  //       voicingID: 3,
  //       tones: "A,C#,E,G",
  //     },
  //     {
  //       strings: "X 0 2 2 2 4",
  //       fingering: "X X 1 1 1 3",
  //       chordName: "A,maj,7,",
  //       enharmonicChordName: "A,maj,7,",
  //       voicingID: 4,
  //       tones: "A,C#,E,G#",
  //     },
  //     {
  //       strings: "X 0 2 0 1 0",
  //       fingering: "X X 2 X 1 X",
  //       chordName: "A,m,7,",
  //       enharmonicChordName: "A,m,7,",
  //       voicingID: 5,
  //       tones: "A,C,E,G",
  //     },
  //     {
  //       strings: "X 0 2 X X X",
  //       fingering: "X X 2 X X X",
  //       chordName: "A,,5,",
  //       enharmonicChordName: "A,,5,",
  //       voicingID: 6,
  //       tones: "A,E",
  //     },
  //     {
  //       strings: "X 0 4 5 4 X",
  //       fingering: "X X 1 3 2 X",
  //       chordName: "A,dim,7,",
  //       enharmonicChordName: "A,dim,7,",
  //       voicingID: 7,
  //       tones: "A,C,Eb,F#",
  //     },
  //     {
  //       strings: "X 0 1 0 1 X",
  //       fingering: "X X 1 X 2 X",
  //       chordName: "A,m,7b5,",
  //       enharmonicChordName: "A,m,7b5,",
  //       voicingID: 8,
  //       tones: "A,C,Eb,G",
  //     },
  //     {
  //       strings: "X 0 2 2 2 2",
  //       fingering: "X X 1 1 1 1",
  //       chordName: "A,,6,",
  //       enharmonicChordName: "A,,6,",
  //       voicingID: 9,
  //       tones: "A,C#,E,F#",
  //     },
  //     {
  //       strings: "X 0 4 5 5 X",
  //       fingering: "X X 1 2 3 X",
  //       chordName: "A,m,6,",
  //       enharmonicChordName: "A,m,6,",
  //       voicingID: 10,
  //       tones: "A,C,E,F#",
  //     },
  //     {
  //       strings: "X 1 3 3 3 1",
  //       fingering: "X 1 2 3 4 1",
  //       chordName: "Bb,,,",
  //       enharmonicChordName: "A#,,,",
  //       voicingID: 11,
  //       tones: "Bb,D,F",
  //     },
  //     {
  //       strings: "X 1 3 3 2 1",
  //       fingering: "X 1 3 4 2 1",
  //       chordName: "Bb,m,,",
  //       enharmonicChordName: "A#,m,,",
  //       voicingID: 12,
  //       tones: "Bb,Db,F",
  //     },
  //     {
  //       strings: "X 1 3 1 3 1",
  //       fingering: "X 1 3 1 4 1",
  //       chordName: "Bb,,7,",
  //       enharmonicChordName: "A#,,7,",
  //       voicingID: 13,
  //       tones: "Bb,D,F,Ab",
  //     },
  //     {
  //       strings: "X 1 3 2 3 1",
  //       fingering: "X 1 3 2 4 1",
  //       chordName: "Bb,maj,7,",
  //       enharmonicChordName: "A#,maj,7,",
  //       voicingID: 14,
  //       tones: "Bb,D,F,A",
  //     },
  //     {
  //       strings: "X 1 3 1 2 1",
  //       fingering: "X 1 3 1 2 1",
  //       chordName: "Bb,m,7,",
  //       enharmonicChordName: "A#,m,7,",
  //       voicingID: 15,
  //       tones: "Bb,Db,F,Ab",
  //     },
  //     {
  //       strings: "X 1 3 X X X",
  //       fingering: "X 1 3 X X X",
  //       chordName: "Bb,,5,",
  //       enharmonicChordName: "A#,,5,",
  //       voicingID: 16,
  //       tones: "Bb,F",
  //     },
  //     {
  //       strings: "X 1 2 0 2 X",
  //       fingering: "X 1 2 X 3 X",
  //       chordName: "Bb,dim,7,",
  //       enharmonicChordName: "A#,dim,7,",
  //       voicingID: 17,
  //       tones: "Bb,Db,E,G",
  //     },
  //     {
  //       strings: "X 1 2 1 2 X",
  //       fingering: "X 1 3 2 4 X",
  //       chordName: "Bb,m,7b5,",
  //       enharmonicChordName: "A#,m,7b5,",
  //       voicingID: 18,
  //       tones: "Bb,Db,E,Ab",
  //     },
  //     {
  //       strings: "X 1 3 0 3 X",
  //       fingering: "X 1 3 X 4 X",
  //       chordName: "Bb,,6,",
  //       enharmonicChordName: "A#,,6,",
  //       voicingID: 19,
  //       tones: "Bb,D,F,G",
  //     },
  //     {
  //       strings: "X 1 3 0 2 X",
  //       fingering: "X 1 4 X 3 X",
  //       chordName: "Bb,m,6,",
  //       enharmonicChordName: "A#,m,6,",
  //       voicingID: 20,
  //       tones: "Bb,Db,F,G",
  //     },
  //     {
  //       strings: "X 2 4 4 4 2",
  //       fingering: "X 1 2 3 4 1",
  //       chordName: "B,,,",
  //       enharmonicChordName: "B,,,",
  //       voicingID: 21,
  //       tones: "B,D#,F#",
  //     },
  //     {
  //       strings: "X 2 4 4 3 2",
  //       fingering: "X 1 3 4 2 1",
  //       chordName: "B,m,,",
  //       enharmonicChordName: "B,m,,",
  //       voicingID: 22,
  //       tones: "B,D,F#",
  //     },
  //     {
  //       strings: "X 2 4 2 4 2",
  //       fingering: "X 1 3 1 4 1",
  //       chordName: "B,,7,",
  //       enharmonicChordName: "B,,7,",
  //       voicingID: 23,
  //       tones: "B,D#,F#,A",
  //     },
  //     {
  //       strings: "X 2 4 3 4 2",
  //       fingering: "X 1 3 2 4 1",
  //       chordName: "B,maj,7,",
  //       enharmonicChordName: "B,maj,7,",
  //       voicingID: 24,
  //       tones: "B,D#,F#,A#",
  //     },
  //     {
  //       strings: "X 2 0 2 0 2",
  //       fingering: "X 2 X 3 X 4",
  //       chordName: "B,m,7,",
  //       enharmonicChordName: "B,m,7,",
  //       voicingID: 25,
  //       tones: "B,D,F#,A",
  //     },
  //     {
  //       strings: "X 2 4 X X X",
  //       fingering: "X 1 3 X X X",
  //       chordName: "B,,5,",
  //       enharmonicChordName: "B,,5,",
  //       voicingID: 26,
  //       tones: "B,F#",
  //     },
  //     {
  //       strings: "X 2 3 1 3 X",
  //       fingering: "X 2 3 1 4 X",
  //       chordName: "B,dim,7,",
  //       enharmonicChordName: "B,dim,7,",
  //       voicingID: 27,
  //       tones: "B,D,F,G#",
  //     },
  //     {
  //       strings: "X 2 3 2 3 X",
  //       fingering: "X 1 3 2 4 X",
  //       chordName: "B,m,7b5,",
  //       enharmonicChordName: "B,m,7b5,",
  //       voicingID: 28,
  //       tones: "B,D,F,A",
  //     },
  //     {
  //       strings: "X 2 1 1 0 2",
  //       fingering: "X 3 1 2 X 4",
  //       chordName: "B,,6,",
  //       enharmonicChordName: "B,,6,",
  //       voicingID: 29,
  //       tones: "B,D#,F#,G#",
  //     },
  //     {
  //       strings: "X 2 4 1 3 X",
  //       fingering: "X 2 4 1 3 X",
  //       chordName: "B,m,6,",
  //       enharmonicChordName: "B,m,6,",
  //       voicingID: 30,
  //       tones: "B,D,F#,G#",
  //     },
  //     {
  //       strings: "X 3 2 0 1 0",
  //       fingering: "X 3 2 X 1 X",
  //       chordName: "C,,,",
  //       enharmonicChordName: "C,,,",
  //       voicingID: 31,
  //       tones: "C,E,G",
  //     },
  //     {
  //       strings: "X 3 5 5 4 3",
  //       fingering: "X 1 3 4 2 1",
  //       chordName: "C,m,,",
  //       enharmonicChordName: "C,m,,",
  //       voicingID: 32,
  //       tones: "C,Eb,G",
  //     },
  //     {
  //       strings: "X 3 2 3 1 0",
  //       fingering: "X 3 2 4 1 X",
  //       chordName: "C,,7,",
  //       enharmonicChordName: "C,,7,",
  //       voicingID: 33,
  //       tones: "C,E,G,Bb",
  //     },
  //     {
  //       strings: "X 3 5 4 5 3",
  //       fingering: "X 1 3 2 4 1",
  //       chordName: "C,maj,7,",
  //       enharmonicChordName: "C,maj,7,",
  //       voicingID: 34,
  //       tones: "C,E,G,B",
  //     },
  //     {
  //       strings: "X 3 5 3 4 3",
  //       fingering: "X 1 3 1 2 1",
  //       chordName: "C,m,7,",
  //       enharmonicChordName: "C,m,7,",
  //       voicingID: 35,
  //       tones: "C,Eb,G,Bb",
  //     },
  //     {
  //       strings: "X 3 5 X X X",
  //       fingering: "X 1 3 X X X",
  //       chordName: "C,,5,",
  //       enharmonicChordName: "C,,5,",
  //       voicingID: 36,
  //       tones: "C,G",
  //     },
  //     {
  //       strings: "X 3 4 2 4 X",
  //       fingering: "X 2 3 1 4 X",
  //       chordName: "C,dim,7,",
  //       enharmonicChordName: "C,dim,7,",
  //       voicingID: 37,
  //       tones: "C,Eb,Gb,A",
  //     },
  //     {
  //       strings: "X 3 4 3 4 X",
  //       fingering: "X 1 3 2 4 X",
  //       chordName: "C,m,7b5,",
  //       enharmonicChordName: "C,m,7b5,",
  //       voicingID: 38,
  //       tones: "C,Eb,Gb,Bb",
  //     },
  //     {
  //       strings: "X 3 X 0 5 5",
  //       fingering: "X 1 X X 3 4",
  //       chordName: "C,,6,",
  //       enharmonicChordName: "C,,6,",
  //       voicingID: 39,
  //       tones: "C,E,G,A",
  //     },
  //     {
  //       strings: "X 3 5 2 4 X",
  //       fingering: "X 2 4 1 3 X",
  //       chordName: "C,m,6,",
  //       enharmonicChordName: "C,m,6,",
  //       voicingID: 40,
  //       tones: "C,Eb,G,A",
  //     },
  //     {
  //       strings: "X 4 3 1 2 1",
  //       fingering: "X 4 3 1 2 1",
  //       chordName: "Db,,,",
  //       enharmonicChordName: "C#,,,",
  //       voicingID: 41,
  //       tones: "Db,F,Ab",
  //     },
  //     {
  //       strings: "X 4 6 6 5 4",
  //       fingering: "X 1 3 4 2 1",
  //       chordName: "Db,m,,",
  //       enharmonicChordName: "C#,m,,",
  //       voicingID: 42,
  //       tones: "C#,E,G#",
  //     },
  //     {
  //       strings: "X 4 6 4 6 4",
  //       fingering: "X 1 3 1 4 1",
  //       chordName: "Db,,7,",
  //       enharmonicChordName: "C#,,7,",
  //       voicingID: 43,
  //       tones: "Db,F,Ab,B",
  //     },
  //     {
  //       strings: "X 4 6 5 6 4",
  //       fingering: "X 1 3 2 4 1",
  //       chordName: "Db,maj,7,",
  //       enharmonicChordName: "C#,maj,7,",
  //       voicingID: 44,
  //       tones: "Db,F,Ab,C",
  //     },
  //     {
  //       strings: "X 4 2 1 0 0",
  //       fingering: "X 4 2 1 X X",
  //       chordName: "Db,m,7,",
  //       enharmonicChordName: "C#,m,7,",
  //       voicingID: 45,
  //       tones: "C#,E,G#,B",
  //     },
  //     {
  //       strings: "X 4 6 X X X",
  //       fingering: "X 1 3 X X X",
  //       chordName: "Db,,5,",
  //       enharmonicChordName: "C#,,5,",
  //       voicingID: 46,
  //       tones: "C#,G#",
  //     },
  //     {
  //       strings: "X 4 5 3 5 X",
  //       fingering: "X 2 3 1 4 X",
  //       chordName: "Db,dim,7,",
  //       enharmonicChordName: "C#,dim,7,",
  //       voicingID: 47,
  //       tones: "C#,E,G,A#",
  //     },
  //     {
  //       strings: "X 4 2 0 0 X",
  //       fingering: "X 4 2 X X X",
  //       chordName: "Db,m,7b5,",
  //       enharmonicChordName: "C#,m,7b5,",
  //       voicingID: 48,
  //       tones: "C#,E,G,B",
  //     },
  //     {
  //       strings: "X 4 6 6 6 6",
  //       fingering: "X 1 3 3 3 3",
  //       chordName: "Db,,6,",
  //       enharmonicChordName: "C#,,6,",
  //       voicingID: 49,
  //       tones: "Db,F,Ab,Bb",
  //     },
  //     {
  //       strings: "X 4 6 3 5 X",
  //       fingering: "X 2 4 1 3 X",
  //       chordName: "Db,m,6,",
  //       enharmonicChordName: "C#,m,6,",
  //       voicingID: 50,
  //       tones: "C#,E,G#,A#",
  //     },
  //     {
  //       strings: "X X 0 2 3 2",
  //       fingering: "X X X 1 3 2",
  //       chordName: "D,,,",
  //       enharmonicChordName: "D,,,",
  //       voicingID: 51,
  //       tones: "D,F#,A",
  //     },
  //     {
  //       strings: "X X 0 2 3 1",
  //       fingering: "X X X 2 3 1",
  //       chordName: "D,m,,",
  //       enharmonicChordName: "D,m,,",
  //       voicingID: 52,
  //       tones: "D,F,A",
  //     },
  //     {
  //       strings: "X X 0 2 1 2",
  //       fingering: "X X X 2 1 3",
  //       chordName: "D,,7,",
  //       enharmonicChordName: "D,,7,",
  //       voicingID: 53,
  //       tones: "D,F#,A,C",
  //     },
  //     {
  //       strings: "X X 0 2 2 2",
  //       fingering: "X X X 2 3 4",
  //       chordName: "D,maj,7,",
  //       enharmonicChordName: "D,maj,7,",
  //       voicingID: 54,
  //       tones: "D,F#,A,C#",
  //     },
  //     {
  //       strings: "X X 0 2 1 1",
  //       fingering: "X X X 2 1 1",
  //       chordName: "D,m,7,",
  //       enharmonicChordName: "D,m,7,",
  //       voicingID: 55,
  //       tones: "D,F,A,C",
  //     },
  //     {
  //       strings: "X X 0 2 X X",
  //       fingering: "X X X 2 X X",
  //       chordName: "D,,5,",
  //       enharmonicChordName: "D,,5,",
  //       voicingID: 56,
  //       tones: "D,A",
  //     },
  //     {
  //       strings: "X X 0 1 0 1",
  //       fingering: "X X X 1 X 2",
  //       chordName: "D,dim,7,",
  //       enharmonicChordName: "D,dim,7,",
  //       voicingID: 57,
  //       tones: "D,F,Ab,B",
  //     },
  //     {
  //       strings: "X X 0 1 1 1",
  //       fingering: "X X X 1 1 1",
  //       chordName: "D,m,7b5,",
  //       enharmonicChordName: "D,m,7b5,",
  //       voicingID: 58,
  //       tones: "D,F,Ab,C",
  //     },
  //     {
  //       strings: "X X 0 2 0 2",
  //       fingering: "X X X 2 X 3",
  //       chordName: "D,,6,",
  //       enharmonicChordName: "D,,6,",
  //       voicingID: 59,
  //       tones: "D,F#,A,B",
  //     },
  //     {
  //       strings: "X X 0 2 0 1",
  //       fingering: "X X X 2 X 1",
  //       chordName: "D,m,6,",
  //       enharmonicChordName: "D,m,6,",
  //       voicingID: 60,
  //       tones: "D,F,A,B",
  //     },
  //     {
  //       strings: "X 6 5 3 4 3",
  //       fingering: "X 4 3 1 2 1",
  //       chordName: "Eb,,,",
  //       enharmonicChordName: "D#,,,",
  //       voicingID: 61,
  //       tones: "Eb,G,Bb",
  //     },
  //     {
  //       strings: "X X 1 3 4 2",
  //       fingering: "X X 1 3 4 2",
  //       chordName: "Eb,m,,",
  //       enharmonicChordName: "D#,m,,",
  //       voicingID: 62,
  //       tones: "Eb,Gb,Bb",
  //     },
  //     {
  //       strings: "X X 1 3 2 3",
  //       fingering: "X X 1 3 2 4",
  //       chordName: "Eb,,7,",
  //       enharmonicChordName: "D#,,7,",
  //       voicingID: 63,
  //       tones: "Eb,G,Bb,Db",
  //     },
  //     {
  //       strings: "X X 1 3 3 3",
  //       fingering: "X X 1 2 3 4",
  //       chordName: "Eb,maj,7,",
  //       enharmonicChordName: "D#,maj,7,",
  //       voicingID: 64,
  //       tones: "Eb,G,Bb,D",
  //     },
  //     {
  //       strings: "X X 1 3 2 2",
  //       fingering: "X X 1 4 2 3",
  //       chordName: "Eb,m,7,",
  //       enharmonicChordName: "D#,m,7,",
  //       voicingID: 65,
  //       tones: "Eb,Gb,Bb,Db",
  //     },
  //     {
  //       strings: "X X 1 3 X X",
  //       fingering: "X X 1 3 X X",
  //       chordName: "Eb,,5,",
  //       enharmonicChordName: "D#,,5,",
  //       voicingID: 66,
  //       tones: "Eb,Bb",
  //     },
  //     {
  //       strings: "X X 1 2 1 2",
  //       fingering: "X X 1 3 2 4",
  //       chordName: "Eb,dim,7,",
  //       enharmonicChordName: "D#,dim,7,",
  //       voicingID: 67,
  //       tones: "Eb,Gb,A,C",
  //     },
  //     {
  //       strings: "X X 1 2 2 2",
  //       fingering: "X X 1 2 3 4",
  //       chordName: "Eb,m,7b5,",
  //       enharmonicChordName: "D#,m,7b5,",
  //       voicingID: 68,
  //       tones: "Eb,Gb,A,Db",
  //     },
  //     {
  //       strings: "X X 1 3 1 3",
  //       fingering: "X X 1 3 1 4",
  //       chordName: "Eb,,6,",
  //       enharmonicChordName: "D#,,6,",
  //       voicingID: 69,
  //       tones: "Eb,G,Bb,C",
  //     },
  //     {
  //       strings: "X X 1 3 1 2",
  //       fingering: "X X 1 3 1 2",
  //       chordName: "Eb,m,6,",
  //       enharmonicChordName: "D#,m,6,",
  //       voicingID: 70,
  //       tones: "Eb,Gb,Bb,C",
  //     },
  //     {
  //       strings: "0 2 2 1 0 0",
  //       fingering: "X 2 3 1 X X",
  //       chordName: "E,,,",
  //       enharmonicChordName: "E,,,",
  //       voicingID: 71,
  //       tones: "E,G#,B",
  //     },
  //     {
  //       strings: "0 2 2 0 0 0",
  //       fingering: "X 2 3 X X X",
  //       chordName: "E,m,,",
  //       enharmonicChordName: "E,m,,",
  //       voicingID: 72,
  //       tones: "E,G,B",
  //     },
  //     {
  //       strings: "0 2 0 1 0 0",
  //       fingering: "X 2 X 1 X X",
  //       chordName: "E,,7,",
  //       enharmonicChordName: "E,,7,",
  //       voicingID: 73,
  //       tones: "E,G#,B,D",
  //     },
  //     {
  //       strings: "0 X 2 4 4 4",
  //       fingering: "X X 1 2 3 4",
  //       chordName: "E,maj,7,",
  //       enharmonicChordName: "E,maj,7,",
  //       voicingID: 74,
  //       tones: "E,G#,B,D#",
  //     },
  //     {
  //       strings: "0 2 0 0 0 0",
  //       fingering: "X 2 X X X X",
  //       chordName: "E,m,7,",
  //       enharmonicChordName: "E,m,7,",
  //       voicingID: 75,
  //       tones: "E,G,B,D",
  //     },
  //     {
  //       strings: "0 2 X X X X",
  //       fingering: "X 2 X X X X",
  //       chordName: "E,,5,",
  //       enharmonicChordName: "E,,5,",
  //       voicingID: 76,
  //       tones: "E,B",
  //     },
  //     {
  //       strings: "0 X 2 3 2 3",
  //       fingering: "X X 1 3 2 4",
  //       chordName: "E,dim,7,",
  //       enharmonicChordName: "E,dim,7,",
  //       voicingID: 77,
  //       tones: "E,G,Bb,C#",
  //     },
  //     {
  //       strings: "0 X 0 3 3 3",
  //       fingering: "X X X 2 3 4",
  //       chordName: "E,m,7b5,",
  //       enharmonicChordName: "E,m,7b5,",
  //       voicingID: 78,
  //       tones: "E,G,Bb,D",
  //     },
  //     {
  //       strings: "0 X 2 4 2 4",
  //       fingering: "X X 1 3 1 4",
  //       chordName: "E,,6,",
  //       enharmonicChordName: "E,,6,",
  //       voicingID: 79,
  //       tones: "E,G#,B,C#",
  //     },
  //     {
  //       strings: "0 2 2 0 2 X",
  //       fingering: "X 2 3 X 4 X",
  //       chordName: "E,m,6,",
  //       enharmonicChordName: "E,m,6,",
  //       voicingID: 80,
  //       tones: "E,G,B,C#",
  //     },
  //     {
  //       strings: "1 3 3 2 1 1",
  //       fingering: "1 3 4 2 1 1",
  //       chordName: "F,,,",
  //       enharmonicChordName: "F,,,",
  //       voicingID: 81,
  //       tones: "F,A,C",
  //     },
  //     {
  //       strings: "1 3 3 1 1 1",
  //       fingering: "1 3 4 1 1 1",
  //       chordName: "F,m,,",
  //       enharmonicChordName: "F,m,,",
  //       voicingID: 82,
  //       tones: "F,Ab,C",
  //     },
  //     {
  //       strings: "1 3 1 2 4 1",
  //       fingering: "1 3 1 2 4 1",
  //       chordName: "F,,7,",
  //       enharmonicChordName: "F,,7,",
  //       voicingID: 83,
  //       tones: "F,A,C,Eb",
  //     },
  //     {
  //       strings: "1 X 2 2 1 0",
  //       fingering: "1 X 3 4 2 X",
  //       chordName: "F,maj,7,",
  //       enharmonicChordName: "F,maj,7,",
  //       voicingID: 84,
  //       tones: "F,A,C,E",
  //     },
  //     {
  //       strings: "1 3 1 1 1 1",
  //       fingering: "1 3 1 1 1 1",
  //       chordName: "F,m,7,",
  //       enharmonicChordName: "F,m,7,",
  //       voicingID: 85,
  //       tones: "F,Ab,C,Eb",
  //     },
  //     {
  //       strings: "1 3 X X X X",
  //       fingering: "1 3 X X X X",
  //       chordName: "F,,5,",
  //       enharmonicChordName: "F,,5,",
  //       voicingID: 86,
  //       tones: "F,C",
  //     },
  //     {
  //       strings: "1 X 0 1 0 X",
  //       fingering: "1 X X 3 X X",
  //       chordName: "F,dim,7,",
  //       enharmonicChordName: "F,dim,7,",
  //       voicingID: 87,
  //       tones: "F,Ab,B,D",
  //     },
  //     {
  //       strings: "1 X 1 1 0 1",
  //       fingering: "1 X 2 3 X 4",
  //       chordName: "F,m,7b5,",
  //       enharmonicChordName: "F,m,7b5,",
  //       voicingID: 88,
  //       tones: "F,Ab,B,Eb",
  //     },
  //     {
  //       strings: "1 X 0 2 1 X",
  //       fingering: "1 X X 4 3 X",
  //       chordName: "F,,6,",
  //       enharmonicChordName: "F,,6,",
  //       voicingID: 89,
  //       tones: "F,A,C,D",
  //     },
  //     {
  //       strings: "1 X 0 1 1 X",
  //       fingering: "1 X X 3 4 X",
  //       chordName: "F,m,6,",
  //       enharmonicChordName: "F,m,6,",
  //       voicingID: 90,
  //       tones: "F,Ab,C,D",
  //     },
  //     {
  //       strings: "2 4 4 3 2 2",
  //       fingering: "1 3 4 2 1 1",
  //       chordName: "Gb,,,",
  //       enharmonicChordName: "F#,,,",
  //       voicingID: 91,
  //       tones: "Gb,Bb,Db",
  //     },
  //     {
  //       strings: "2 4 4 2 2 2",
  //       fingering: "1 3 4 1 1 1",
  //       chordName: "Gb,m,,",
  //       enharmonicChordName: "F#,m,,",
  //       voicingID: 92,
  //       tones: "F#,A,C#",
  //     },
  //     {
  //       strings: "2 4 2 3 5 2",
  //       fingering: "1 3 1 2 4 1",
  //       chordName: "Gb,,7,",
  //       enharmonicChordName: "F#,,7,",
  //       voicingID: 93,
  //       tones: "F#,A#,C#,E",
  //     },
  //     {
  //       strings: "2 X 3 3 2 X",
  //       fingering: "1 X 3 4 2 X",
  //       chordName: "Gb,maj,7,",
  //       enharmonicChordName: "F#,maj,7,",
  //       voicingID: 94,
  //       tones: "Gb,Bb,Db,F",
  //     },
  //     {
  //       strings: "2 4 2 2 2 2",
  //       fingering: "1 3 1 1 1 1",
  //       chordName: "Gb,m,7,",
  //       enharmonicChordName: "F#,m,7,",
  //       voicingID: 95,
  //       tones: "F#,A,C#,E",
  //     },
  //     {
  //       strings: "2 4 X X X X",
  //       fingering: "1 3 X X X X",
  //       chordName: "Gb,,5,",
  //       enharmonicChordName: "F#,,5,",
  //       voicingID: 96,
  //       tones: "F#,C#",
  //     },
  //     {
  //       strings: "2 X 1 2 1 X",
  //       fingering: "2 X 1 4 1 X",
  //       chordName: "Gb,dim,7,",
  //       enharmonicChordName: "F#,dim,7,",
  //       voicingID: 97,
  //       tones: "F#,A,C,D#",
  //     },
  //     {
  //       strings: "2 X 2 2 1 0",
  //       fingering: "2 X 3 4 1 X",
  //       chordName: "Gb,m,7b5,",
  //       enharmonicChordName: "F#,m,7b5,",
  //       voicingID: 98,
  //       tones: "F#,A,C,E",
  //     },
  //     {
  //       strings: "2 X 1 3 2 X",
  //       fingering: "2 X 1 4 3 X",
  //       chordName: "Gb,,6,",
  //       enharmonicChordName: "F#,,6,",
  //       voicingID: 99,
  //       tones: "Gb,Bb,Db,Eb",
  //     },
  //     {
  //       strings: "2 X 1 2 2 X",
  //       fingering: "2 X 1 3 4 X",
  //       chordName: "Gb,m,6,",
  //       enharmonicChordName: "F#,m,6,",
  //       voicingID: 100,
  //       tones: "F#,A,C#,D#",
  //     },
  //     {
  //       strings: "3 2 0 0 3 3",
  //       fingering: "2 1 X X 3 4",
  //       chordName: "G,,,",
  //       enharmonicChordName: "G,,,",
  //       voicingID: 101,
  //       tones: "G,B,D",
  //     },
  //     {
  //       strings: "3 5 5 3 3 3",
  //       fingering: "1 3 4 1 1 1",
  //       chordName: "G,m,,",
  //       enharmonicChordName: "G,m,,",
  //       voicingID: 102,
  //       tones: "G,Bb,D",
  //     },
  //     {
  //       strings: "3 2 0 0 0 1",
  //       fingering: "3 2 X X X 1",
  //       chordName: "G,,7,",
  //       enharmonicChordName: "G,,7,",
  //       voicingID: 103,
  //       tones: "G,B,D,F",
  //     },
  //     {
  //       strings: "3 X 4 4 3 X",
  //       fingering: "1 X 3 4 2 X",
  //       chordName: "G,maj,7,",
  //       enharmonicChordName: "G,maj,7,",
  //       voicingID: 104,
  //       tones: "G,B,D,F#",
  //     },
  //     {
  //       strings: "3 5 3 3 3 3",
  //       fingering: "1 3 1 1 1 1",
  //       chordName: "G,m,7,",
  //       enharmonicChordName: "G,m,7,",
  //       voicingID: 105,
  //       tones: "G,Bb,D,F",
  //     },
  //     {
  //       strings: "3 5 X X X X",
  //       fingering: "1 3 X X X X",
  //       chordName: "G,,5,",
  //       enharmonicChordName: "G,,5,",
  //       voicingID: 106,
  //       tones: "G,D",
  //     },
  //     {
  //       strings: "3 X 2 3 2 X",
  //       fingering: "2 X 1 4 1 X",
  //       chordName: "G,dim,7,",
  //       enharmonicChordName: "G,dim,7,",
  //       voicingID: 107,
  //       tones: "G,Bb,Db,E",
  //     },
  //     {
  //       strings: "3 X 3 3 2 X",
  //       fingering: "2 X 3 4 1 X",
  //       chordName: "G,m,7b5,",
  //       enharmonicChordName: "G,m,7b5,",
  //       voicingID: 108,
  //       tones: "G,Bb,Db,F",
  //     },
  //     {
  //       strings: "3 X 0 0 0 0",
  //       fingering: "3 X X X X X",
  //       chordName: "G,,6,",
  //       enharmonicChordName: "G,,6,",
  //       voicingID: 109,
  //       tones: "G,B,D,E",
  //     },
  //     {
  //       strings: "3 X 2 3 3 X",
  //       fingering: "2 X 1 3 4 X",
  //       chordName: "G,m,6,",
  //       enharmonicChordName: "G,m,6,",
  //       voicingID: 110,
  //       tones: "G,Bb,D,E",
  //     },
  //     {
  //       strings: "4 6 6 5 4 4",
  //       fingering: "1 3 4 2 1 1",
  //       chordName: "Ab,,,",
  //       enharmonicChordName: "G#,,,",
  //       voicingID: 111,
  //       tones: "Ab,C,Eb",
  //     },
  //     {
  //       strings: "4 6 6 4 4 4",
  //       fingering: "1 3 4 1 1 1",
  //       chordName: "Ab,m,,",
  //       enharmonicChordName: "G#,m,,",
  //       voicingID: 112,
  //       tones: "G#,B,D#",
  //     },
  //     {
  //       strings: "4 6 4 5 7 4",
  //       fingering: "1 3 1 2 4 1",
  //       chordName: "Ab,,7,",
  //       enharmonicChordName: "G#,,7,",
  //       voicingID: 113,
  //       tones: "Ab,C,Eb,Gb",
  //     },
  //     {
  //       strings: "4 X 5 5 4 X",
  //       fingering: "1 X 3 4 2 X",
  //       chordName: "Ab,maj,7,",
  //       enharmonicChordName: "G#,maj,7,",
  //       voicingID: 114,
  //       tones: "Ab,C,Eb,G",
  //     },
  //     {
  //       strings: "4 6 4 4 4 4",
  //       fingering: "1 3 1 1 1 1",
  //       chordName: "Ab,m,7,",
  //       enharmonicChordName: "G#,m,7,",
  //       voicingID: 115,
  //       tones: "G#,B,D#,F#",
  //     },
  //     {
  //       strings: "4 6 X X X X",
  //       fingering: "1 3 X X X X",
  //       chordName: "Ab,,5,",
  //       enharmonicChordName: "G#,,5,",
  //       voicingID: 116,
  //       tones: "G#,D#",
  //     },
  //     {
  //       strings: "4 X 3 4 3 X",
  //       fingering: "2 X 1 4 1 X",
  //       chordName: "Ab,dim,7,",
  //       enharmonicChordName: "G#,dim,7,",
  //       voicingID: 117,
  //       tones: "G#,B,D,F",
  //     },
  //     {
  //       strings: "4 X 4 4 3 X",
  //       fingering: "2 X 3 4 1 X",
  //       chordName: "Ab,m,7b5,",
  //       enharmonicChordName: "G#,m,7b5,",
  //       voicingID: 118,
  //       tones: "G#,B,D,F#",
  //     },
  //     {
  //       strings: "4 X 3 5 4 X",
  //       fingering: "2 X 1 4 3 X",
  //       chordName: "Ab,,6,",
  //       enharmonicChordName: "G#,,6,",
  //       voicingID: 119,
  //       tones: "Ab,C,Eb,F",
  //     },
  //     {
  //       strings: "4 X 3 4 4 X",
  //       fingering: "2 X 1 3 4 X",
  //       chordName: "Ab,m,6,",
  //       enharmonicChordName: "G#,m,6,",
  //       voicingID: 120,
  //       tones: "G#,B,D#,F",
  //     },
  //   ],
  // });
  const allChords = await prisma.chords.findMany();
  console.log(allChords);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
